# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  testProject: ./product-api-test/bootcamp-webapi-test.csproj
  applicationProject: ./product-api/bootcamp-webapi.csproj

jobs:
- job: Build
  steps:
  - task: UseDotNet@2
    inputs:
      version: '3.1.x'
      packageType: sdk

  - script: |
      echo "Retrieving external libraries..."
      cd product-api
      dotnet restore
    displayName: 'Resolve Dependencies'

  - script: |
      echo "Building projects..."
      cd product-api
      dotnet build --configuration $(buildConfiguration)
    displayName: 'Build Source'

  - script: |
      echo "Creating final application package..."
      dotnet publish $(applicationProject) -o ./publish --configuration $(buildConfiguration)
    displayName: 'Package Application'
    
  - task: CopyFiles@2
    inputs:
      contents: publish/**
      targetFolder: $(Build.ArtifactStagingDirectory)
      CleanTargetFolder: true
    displayName: 'Stage Application Package'
    
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: ADOBuildOutput
    displayName: 'Publish Build Package'
    
- job: Test
  dependsOn: Build
  steps:
  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'ADOBuildOutput'
      downloadPath: '$(Build.SourcesDirectory)'
    
  - script: |
      echo "Running tests..."
      dotnet test $(testProject)
    displayName: 'Execute Tests'

- job: Image
  dependsOn: Test
  steps:
  - task: KubernetesManifest@0
    inputs:
      action: 'deploy'
      kubernetesServiceConnection: 'dev-builds-1610766962428'
      namespace: 'builds'
      manifests: './image.yml'
  
  - script: |
      echo "Creating image..."
    displayName: 'Create Image'